mysql:
  prefix: quest_
default_journal_slot: '-1'
max_npc_distance: '5'
citizens_npcs_by_name: 'false'
default_conversation_IO: screen
default_interceptor: packet,simple
display_chat_after_conversation: 'true'
combat_delay: '10'
notify_pullback: 'true'
remove_items_after_respawn: 'true'
quest_items_unbreakable: 'true'
sounds:
  start: BLOCK_NOTE_HARP
  end: BLOCK_NOTE_BELL
  journal: ENTITY_BAT_TAKEOFF
  update: 'false'
  full: 'false'
cmd_blacklist:
- spawn
hook:
  citizens: true
  mythicmobs: true
  vault: true
  worldguard: true
  placeholderapi: true
  holographicdisplays: true
  worldedit: true
  protocollib: true
journal:
  chars_per_line: '19'
  lines_per_page: '13'
  one_entry_per_page: 'false'
  reversed_order: 'true'
  hide_date: 'false'
  full_main_page: 'false'
journal_colors:
  date:
    day: '9'
    hour: '6'
  line: '4'
  text: '0'
conversation_colors:
  npc: dark_red
  player: dark_green
  text: green,italic
  answer: gray
  number: yellow
  option: aqua
date_format: dd.MM.yyyy HH:mm