name: BetonQuest
main: pl.betoncraft.betonquest.BetonQuest
api-version: 1.13
description: Advanced role-playing quests and NPC conversations
authors: [Co0sh, justwei]
depend:
  - DataManager
  - MegumiLib
  - Zaphkiel
  - JustMessage
  - JustAttribute
  - GemsEconomy
  - EternalCargo
  - Waypoints
softdepend:
  - Citizens
  - MythicMobs
  - Vault
  - WorldEdit
  - WorldGuard
  - PlaceholderAPI
  - HolographicDisplays
  - ProtocolLib
  - JustStore
version: ${project.version}
commands:
  betonquest:
    description: General quest command
    usage: /<command>
    permission: betonquest.admin
    aliases: [bq, quest]
permissions:
  betonquest.admin:
    default: op
  
